### ISSUE TITLE
Support for the `bounds` serde attribute.

### ISSUE THREAD

**Issue by abizjak** [GREsau/schemars#137]
It is sometimes necessary to have either phantom types or special bounds for types for the structs. `serde` supports supplying custom bounds on these types so that the derived instance has useful bounds, instead of requiring all type parameters to have the `Serialize/Deserialize` bounds. 

It does not appear that `schemars` honors these.

Concretely, I would like this to work
```rust
#[derive(Serialize, Deserialize)]
#[derive(JsonSchema)] 
#[serde(bound = "A: Sized")]
struct S<A> {
    x: u64,
    #[serde(skip)]
    a: PhantomData<A>
}

struct Dummy;

fn f() {
    let schema = schema_for!(S<Dummy>);
}
```

**Comment by GREsau** [comment]
This is already supported via the `#[schemars(bound = "...")]` attribute - see https://graham.cool/schemars/deriving/attributes/#bound

As the docs say:
>  Schemars does not use trait bounds from #[serde(bound)] attributes.

This is because in many cases, the bounds needed for `De/Serialize` would be different to the bounds needed for `JsonSchema`.

So in your case, you would need to add `#[schemars(bound = "A: Sized")]`

However, a nice enhancement would be to improve the automatically-generated bounds to be smarter, e.g. ignore `PhantomData` fields. This wouldn't be easy, but is certainly possible - and fortunately can mostly be done by [copying what serde does](https://github.com/serde-rs/serde/blob/1b4da41f970555e111f471633205bbcb4dadbc63/serde_derive/src/bound.rs#L126) 😄

**Comment by GREsau** [comment]
I just noticed that I'd already created an issue for improving automatic trait bounds (#168) so I'll close this in favour of that
