### ISSUE TITLE
numeric constraints always converted to floats

### ISSUE THREAD

**Issue by kstasik** [GREsau/schemars#181]
Problem:

Current implementation of library doesn't distinguish between integers and numbers in case of validation:

https://json-schema.org/understanding-json-schema/reference/numeric.html

https://github.com/GREsau/schemars/blob/master/schemars/src/schema.rs#L360-L386

It causes issues if you want to use this library with more strict structures.

Solution:

Add separate support for integers and numbers so it doesn't add .0 to json serialised schemas:

https://github.com/GREsau/schemars/blob/master/schemars/tests/expected/duration_and_systemtime.json#L28

**Comment by GREsau** [comment]
In schemars 1.0.0-alpha.1 (and later), schemas are wrappers around a `serde_json::Value`, which means that numbers are now `serde_json::Number`s instead of being forced to floats. Conveniently, this means that they are typically serialized as plain integers where appropriate, e.g. https://github.com/GREsau/schemars/blob/705aba1cef4ad4de3436a707b3e0644cd5c977c5/schemars/tests/expected/duration_and_systemtime.json#L29
