### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by webmaster128** [GREsau/schemars#22]
Thanks for this great project. At https://github.com/CosmWasm/cosmwasm/issues/168 we are planning the upgrade to 0.6 or 0.7, but a bit unsure which code branch to use. Is anything missing for a 0.7.0 freeze? Apha versions are online for a couple of months now.

Cheers

**Comment by GREsau** [comment]
The only other breaking change I was planning on making in 0.7.0 would be to primarily using `$defs` instead of `definitions`, in order to align more closely with JSON Schema version 2019-09. I started making changes to support this in the [`rename-definitions`](https://github.com/GREsau/schemars/tree/rename-definitions) branch, but I wasn't very happy with the interface, so I left it for a while.

Given no-one's really asked for that change, I don't think it's worth putting too much more effort into it right now, nor is it worth holding up 0.7.0 any more for it.

So I'll publish the current master branch to crates.io as 0.7.0 when I get a chance - I'll leave this issue open until it's published

**Comment by GREsau** [comment]
Done! https://crates.io/crates/schemars/0.7.0

**Comment by webmaster128** [comment]
Thanks! I don't know much about the JSON schema standard and how it evolved. I'm sure you know that much better and made a reasonable decision. Right now we're happy with draft 7 schemars.
