### ISSUE TITLE
gen keyword is reserved in Rust 2024

### ISSUE THREAD

**Issue by azat** [GREsau/schemars#306]
There are couple of issues with schemars and rust 2024:
- usage of `schemars::gen::SchemaGenerator` requires ugly syntax `schemars::r#gen::SchemaGenerator`
- the derive macro generates `gen` inside, so it is unusable in 2024

I guess it is better to rename the gen module? Objections?

**Comment by GREsau** [comment]
I think my preferred fix to this would be to make `SchemaSettings` available from the crate root (`SchemaGenerator` is already available from the crate root) so that it can be imported as `use schemars::SchemaSettings`.

And obviously schemars_derive would need updating to not use the `gen` module (or any variables called `gen`)

**Comment by GREsau** [comment]
This is fixed in 1.0.0-alpha.8 - the `gen` module is now replaced by the `generate` module. For now, `gen` is still available as as a deprecated alias for the sake of backward-compatibility
