### ISSUE TITLE
`JsonSchema` trait with `erased_serde` (object safety)

### ISSUE THREAD

**Issue by IzawGithub** [GREsau/schemars#332]
Hello, thank you for the crate! It's really useful to make configuration tool.

I'm currently a bit stumped on an issue I have.
I've got a configuration struct that stores a lot of info. For multiple reason, I'm currently working on moving away from generic, to dynamic traits. So I've changed my config struct from this:

```rust
// Before
#[derive(Deserialize, Serialize, JsonSchema)]
struct Config<ProvidedByDownstream: JsonSchema> {
    pub downstream: ProvidedByDownstream
}

// Now
#[typetag::serde]
pub trait ProvidedByDownstream: JsonSchema {}

#[derive(Deserialize, Serialize, JsonSchema)]
struct Config {
    pub downstream: Box<dyn ProvidedByDownstream> 
}
```

Problem is, I can't add `JsonSchema` as a supertrait, as it is not object safe.
Looking very briefly at how `JsonSchema` is defined, the main problem seems to be no `self` receiver for the defined methods. There's probably more showstoppers, but I wanted your opinion on the feasibility before I even try to tackle this.
Would making `JsonSchema` object safe even be possible?

**Comment by GREsau** [comment]
I don't fully understand what you're trying to do, but the short answer is: No, it's not really possible to make `JsonSchema` object-safe, because all of its behaviour relates to the type on which its implemented rather than individual instances of that type.

Considering the problem at a higher level - what you would expect the generated schema for `Config` to look like? It could be something like `{ "anyOf": [ ... ] }`, where the array contents are the schemas for all possible types that implement `ProvidedByDownstream` - but schemars has no way of "knowing" what all of those types are.

`serde::Deserialize` would have the same problem, but you're obviously working around that with [typetag](https://github.com/dtolnay/typetag). Theoretically it would be possible to solve this problem in a similar way - by introducing an attribute macro that collects all types that implement your trait, and then implements `JsonSchema` for `dyn ProvidedByDownstream` by enumerating those types and putting their schemas in an `"anyOf"` like the example above. I have no plans to implement such a thing, and given the complexity I wouldn't want to include it in schemars for what is a relatively niche use-case - but you may want to try implementing it yourself (the "how does it work" at the bottom of the typetag readme  gives a good overview).

Or for a quick (but obviously less accurate) workaround, you could of course treat the `Box<dyn ProvidedByDownstream>` as "any value" e.g.
```rust
pub trait ProvidedByDownstream {}

#[derive(JsonSchema)]
struct Config {
    #[schemars(with = "serde_json::Value")]
    pub downstream: Box<dyn ProvidedByDownstream>,
}
```
