### ISSUE TITLE
Generated schema seems to be invalid

### ISSUE THREAD

**Issue by sphinxc0re** [GREsau/schemars#43]
When I try to use the generated schema to validate data using [Ajv](https://github.com/ajv-validator/ajv) I'm getting the following error:
```
Error: unknown format "uint32" is used in schema at path [...]
```
The error seems to be related to the integer format attribute. I couldn't find any mention of `uint32`, `uint` or anything of sorts in the JsonSchema spec.

Here is an example of the generated schema: 
```json
"portal": {
          "type": "integer",
          "format": "uint32",
          "minimum": 0.0
        },
```

Am I doing something wrong here or is this a bug?

**Comment by GREsau** [comment]
While uint32 is not a standard `format` value, I believe including it is still valid and useful to convey a suitable storage type of such a property (e.g. a program that generates rust code from a schema could use such a format to create a u32 field corresponding to that "portal" property).

My choice of calling that particular format "uint32" was to be as consistent as possible with the heavily used "int32"/"int64" formats [defined by OpenAPI](https://swagger.io/specification/).

Draft 7 of the JSON Schema specification explicitly says "Implementations MAY add custom format attributes" ([link](https://tools.ietf.org/html/draft-handrews-json-schema-validation-01#section-7.2))

Draft 2019-09 (the latest version) adds "An implementation MUST NOT fail validation or cease processing due to an unknown format attribute" ([link](https://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.7.2.3)), so technically Ajv is deviating from the spec by raising an error here - although I can see the maintainer [brings up some fair reasons to do so](https://github.com/ajv-validator/ajv/issues/466#issuecomment-296290767).

As for your specific issue, I think you could workaround it in Ajv by adding the "uint32" format using the [addFormat](https://github.com/ajv-validator/ajv#addformatstring-name-stringregexpfunctionobject-format---ajv) method e.g. `ajv.addFormat('uint32', /\d+/)`, or by disabling the [unknownFormat option](https://github.com/ajv-validator/ajv#options)

**Comment by sphinxc0re** [comment]
Thanks for the help. It all works fine now.
