### ISSUE TITLE
Rust type names are not preserved

### ISSUE THREAD

**Issue by ufoscout** [GREsau/schemars#71]
In case of an exported Rust type, the generated schema does not respect its name.
For example:
```rust
#[derive(Serialize, Deserialize, JsonSchema)]
pub struct MyObject<D> {
    pub data: D,
}

pub type MyObjectType = MyObject<String>;

fn main() {
    let alias_schema = schema_for!(MyObjectType);
    println!("schema: \n{:?}", serde_json::to_string_pretty(&alias_schema).unwrap());
}
```
In this example, the object's name in the schema is `MyObject_for_String`, would it be possible instead to use `MyObjectType` as name?

Nevertheless, I am not sure if this can be achieved in Rust.

**Comment by GREsau** [comment]
I'm not sure what the "best" behaviour is for this, since `MyObjectType` and `MyObject<String>` are the same type, so it kinda makes sense that they generate the exact same schema.

For now I think I'd rather keep the current behaviour where it uses the "original" type name. But you could achieve what you want by using your own macro that modifies the title of the generated schema to whatever literal you pass into the macro:
```rust
macro_rules! named_schema_for {
    ($type:ty) => {{
        let mut root_schema = schemars::schema_for!($type);
        root_schema.schema.metadata().title = Some(stringify!($type).to_string());
        root_schema
    }};
}
```

**Comment by ufoscout** [comment]
@GREsau 
While I agree that they are the same type, the current behaviour does not correctly highlight the fact that there could be changes between versions of the schema.

For example, suppose this is the struct definition in version-1:
```rust
pub type MyObjectType = MyObject<String>;
```

and imagine there is a breaking change like one this in version-2:
```rust
pub type MyObjectType = MyObject<bool>;
```

Then consumers of the schema will not be aware of the change; in fact, they will keep using `MyObject_for_String`. On the contrary, if the consumers are using `MyObjectType`, then they will get a compilation error that informs them that the object definition has changed.

In our case, we have a client written in TypeScript that could have failed to compile when we performed a similar change in the schema; instead, it compiled perfectly and caused a bug at runtime.

**Comment by ripytide** [comment]
I recently ran into this issue and was quite surprised at the default behavior of using the "raw" type as the type name rather than the used type synonym name.

Similar to @ufoscout I have a TS client that is using my schema and I find it not very ergonomic to write `ResultOf_ArrayOf_ResultOf_TimetablerOutputOr_TimetablerErrorOr_ArrayOf_ResultOf_TimetablerOutputOr_TimetablerError` rather than it's type synonym `SimulationResult`.

I was thinking about how this would be possible to implement. Simple recursion wouldn't work as if you had `type A = i32` and `type B = i32` then when you called `json_schema<A>()` you are really calling `json_schema<i32>()` which will have a `metadata.title` of `"i32"`. So it wouldn't be possible that way but it would be possible via indirect recursion where if you have a struct like `struct MyStruct(A)` then the implementation of `JsonScema` on this struct have access to the AST (I believe?) so it would be able to generate a "type synonym schema" (if it doesn't already exist) that simply points to the "raw" type that can also be generated (if it doesn't already exist in dependencies).

Could adding this behavior as an option to `SchemaSettings` be opened as a feature request @GREsau?

Please bear in mind I have next to no experience in this area of rust and everything I just said may likely be utter balderdash.
